### ISSUE TITLE
Auslagern aller Config Objekte in json datei(en)

### ISSUE THREAD

**Issue by desertfox94** [TetrisIQ/PSG#1]
Ist ein schöner Ansatz das ganze über eine JSON Konfiguration zu lösen! Aber warum hast du nicht alle in eine Config datei ausgelagert sondern nur das root element?

https://github.com/TetrisIQ/PSG/blob/aead5cca41dfef3cda894445ea24d3e3080fb03f/src/main/java/de/edu/game/config/loader/ConfigLoader.java#L48

**Comment by TetrisIQ** [comment]
Es ist nicht nur das Root Element ausgelagert. Die ganze Klasse kann über die JSON datei konfiguriert werden. Ich habe Zuweisungen gemacht damit nicht zwingend eine konfig benötigt wird. Alle zuweisungen Spiegeln Default werte dar. Soll die `spaceStation` angepasst werden müsste in der config nur 
```json
...

"spaceStation"  :  {
    "name" : "SpaceStation",
    "hp" : 100,
    "damage" : "1w10+10",
    "defense" : "1w10+10",
    "attackRange" : 1,
    "coasts" : 0
}
...
```
