### ISSUE TITLE
ArrayList statt LinkedList

### ISSUE THREAD

**Issue by desertfox94** [TetrisIQ/PSG#13]
Du weißt zu beginn wie große die Map sein soll und erzeugst sie auch nur einmal. Du kannst also definitiv eine ArrayList nehmen, das macht den Zugriff schneller.

https://github.com/TetrisIQ/PSG/blob/514aa2c60b3e49f5de5e2555a155c9d01dd196ad/src/main/java/de/edu/game/model/Map.java#L31

**Comment by TetrisIQ** [comment]
Ich weiß nicht genau wieso, aber ich nehme aus Gewohnheit immer ein `LinkedList`, ohne darüber nachzudenken. Aber ja eine `ArrayList` ist schneller und ich denke das sollte schon ein wenig performanter sein da besonderes bei der `map` sehr oft auf die listen zugegriffen wird.
