### ISSUE TITLE
Immer das erste Spiel

### ISSUE THREAD

**Issue by desertfox94** [TetrisIQ/PSG#3]
es wird immer das erste Spiel in der Datenbank gegriffen.

https://github.com/TetrisIQ/PSG/blob/aead5cca41dfef3cda894445ea24d3e3080fb03f/src/main/java/de/edu/game/config/loader/ConfigLoader.java#L48

**Comment by TetrisIQ** [comment]
Ich denke, du meinst hier,
https://github.com/TetrisIQ/PSG/blob/514aa2c60b3e49f5de5e2555a155c9d01dd196ad/src/main/java/de/edu/game/repositorys/GameRepository.java#L10

Das passt aber soweit da es immer nur ein Game gibt
