### ISSUE TITLE
MineSpeed und Storage des Transporters

### ISSUE THREAD

**Issue by desertfox94** [TetrisIQ/PSG#6]
müsste es nicht `if(this.storage + this.mineSpeed < this.maxStorage)` lauten? Oder zumindest mineSpeed beim minen gedeckelt werden? Also:
```java
int storageLeft = this.maxStorage - this.storage;
int nextMining = storageLeft < this.mineSpeed ? storageLeft : this.mineSpeed;
int mine = asteroid.mine(nextMining);
this.storage **+**= mine; // und hier fehlt das + oder?
```

https://github.com/TetrisIQ/PSG/blob/514aa2c60b3e49f5de5e2555a155c9d01dd196ad/src/main/java/de/edu/game/model/Transporter.java#L79

**Comment by TetrisIQ** [comment]
Ja das ist ein guter Punkt und + fehlte wirklich.
Wäre tatsächlich sehr spät aufgefallen da derzeit `mineSpeed` und `maxStorage` gleich groß sind. Es also im Transporter eigentlich nur voll und leer gibt, aber eigentlich ist das anderes gedacht. 
Danke für den Tipp :)
