### ISSUE TITLE
makeDamage() Prüfung auf < 0

### ISSUE THREAD

**Issue by desertfox94** [TetrisIQ/PSG#9]
Bei makeDamager lohnt es sich auf < 0 zu prüfen. Ansonsten kann schaden das Meeple heilen.

```
    public int makeDamage(int damage) {
        if (damage < 0) throw new RuntimeException("Damage can not be smaller than zero");
        this.hp -= damage;
        return this.hp;
    }
```

https://github.com/TetrisIQ/PSG/blob/514aa2c60b3e49f5de5e2555a155c9d01dd196ad/src/main/java/de/edu/game/model/AbstractMeeple.java#L141

**Comment by TetrisIQ** [comment]
Guter punkt :smile:
